# My numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr= np.array([1,3,4,5,6], np.int8)

In [3]:
myarr[4]

6

In [4]:
myarr.shape

(5,)

In [5]:
myarr.dtype

dtype('int8')

In [6]:
myarr[4]=25

In [7]:
myarr

array([ 1,  3,  4,  5, 25], dtype=int8)

# Array creation : conversion from the other python structure


In [8]:
listarray = np.array([[1,2,3,4],[2,4,6,8],[5,6,8,7]])

In [9]:
listarray

array([[1, 2, 3, 4],
       [2, 4, 6, 8],
       [5, 6, 8, 7]])

In [10]:
listarray.shape

(3, 4)

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.size

12

In [13]:
listarray[1,3]=25

In [15]:
listarray

array([[ 1,  2,  3,  4],
       [ 2,  4,  6, 25],
       [ 5,  6,  8,  7]])

In [26]:
five = np.zeros((3,3))

In [27]:
five

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])